In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv


## Importing Libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
train_dataset = pd.read_csv('../input/titanic/train.csv')
train_dataset['Sex'].replace(['male', 'female'],[0, 1], inplace=True)
test_dataset = pd.read_csv('../input/titanic/test.csv')
test_dataset['Sex'].replace(['male', 'female'],[0, 1], inplace=True)
Y_train_dev = train_dataset.iloc[:,1].values
X_train_dev = train_dataset.iloc[:,[2,4,5,6,7,9]]
X_test = test_dataset.iloc[:,[1,3,4,5,6,8]]
output = np.zeros([X_test.shape[0],2])
output[:,0] = test_dataset.iloc[:,0]

## Splitting into dev and train set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_dev, Y_train, Y_dev = train_test_split(X_train_dev, Y_train_dev, test_size = 0.11235, random_state = 0) 

In [5]:
print(X_train)

     Pclass  Sex   Age  SibSp  Parch     Fare
249       2    0  54.0      1      0  26.0000
715       3    0  19.0      0      0   7.6500
175       3    0  18.0      1      1   7.8542
251       3    1  29.0      1      1  10.4625
279       3    1  35.0      1      1  20.2500
..      ...  ...   ...    ...    ...      ...
835       1    1  39.0      1      1  83.1583
192       3    1  19.0      1      0   7.8542
629       3    0   NaN      0      0   7.7333
559       3    1  36.0      1      0  17.4000
684       2    0  60.0      1      1  39.0000

[790 rows x 6 columns]


In [6]:
print(Y_train)

[0 0 0 0 1 1 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 1 0 0 1 1 0 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 1
 0 0 0 0 0 1 0 1 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 0 1 1 0 0 0
 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0
 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 0 0 1 1 1 0 0 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1
 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 1 0 0 0 1 1 0 0 1 0 1 0 0 0
 0 1 1 1 0 1 0 1 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1 0
 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 1
 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 1
 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1
 0 1 0 0 1 0 1 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1 0 0 0
 0 1 1 0 0 1 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0
 0 0 0 1 1 0 0 0 1 0 0 0 

In [7]:
print(X_test)

     Pclass  Sex   Age  SibSp  Parch      Fare
0         3    0  34.5      0      0    7.8292
1         3    1  47.0      1      0    7.0000
2         2    0  62.0      0      0    9.6875
3         3    0  27.0      0      0    8.6625
4         3    1  22.0      1      1   12.2875
..      ...  ...   ...    ...    ...       ...
413       3    0   NaN      0      0    8.0500
414       1    1  39.0      0      0  108.9000
415       3    0  38.5      0      0    7.2500
416       3    0   NaN      0      0    8.0500
417       3    0   NaN      1      1   22.3583

[418 rows x 6 columns]


## Taking Care of Missing Data

In [8]:
from sklearn.impute import SimpleImputer
imputer1 = SimpleImputer(missing_values=np.nan,strategy = 'median')
imputer1.fit(X_train)
imputer2 = SimpleImputer(missing_values=np.nan,strategy = 'median')
imputer2.fit(X_test)
X_train = imputer1.transform(X_train)
X_dev = imputer1.transform(X_dev) 
X_test = imputer2.transform(X_test)

In [9]:
print(X_train)

[[ 2.      0.     54.      1.      0.     26.    ]
 [ 3.      0.     19.      0.      0.      7.65  ]
 [ 3.      0.     18.      1.      1.      7.8542]
 ...
 [ 3.      0.     29.      0.      0.      7.7333]
 [ 3.      1.     36.      1.      0.     17.4   ]
 [ 2.      0.     60.      1.      1.     39.    ]]


In [10]:
print(X_dev)

[[  3.       0.      29.       0.       0.      14.4583]
 [  3.       0.      29.       0.       0.       7.55  ]
 [  3.       0.       7.       4.       1.      29.125 ]
 [  1.       1.      29.       1.       0.     146.5208]
 [  3.       1.      29.       0.       2.      15.2458]
 [  1.       0.      29.       0.       0.      30.5   ]
 [  1.       1.      40.       0.       0.     153.4625]
 [  1.       1.      31.       0.       2.     164.8667]
 [  1.       0.      25.       1.       0.      91.0792]
 [  3.       1.      29.       0.       0.       7.2292]
 [  3.       0.      26.       1.       0.       7.8542]
 [  2.       1.      40.       0.       0.      13.    ]
 [  3.       0.      29.       0.       0.       7.75  ]
 [  2.       1.       7.       0.       2.      26.25  ]
 [  1.       1.      24.       0.       0.      83.1583]
 [  3.       1.      14.       0.       0.       7.8542]
 [  3.       0.      23.       0.       0.       9.225 ]
 [  2.       0.      19.       

In [11]:
print(X_test)

[[ 3.      0.     34.5     0.      0.      7.8292]
 [ 3.      1.     47.      1.      0.      7.    ]
 [ 2.      0.     62.      0.      0.      9.6875]
 ...
 [ 3.      0.     38.5     0.      0.      7.25  ]
 [ 3.      0.     27.      0.      0.      8.05  ]
 [ 3.      0.     27.      1.      1.     22.3583]]


## Training Model

In [12]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

## Making the Confusion Matrix

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_dev_pred = classifier.predict(X_dev)
cm = confusion_matrix(Y_dev,Y_dev_pred)
print(cm)
accuracy_score(Y_dev,Y_dev_pred)

[[53  5]
 [14 29]]


0.8118811881188119

## Predicting Test Set Results

In [14]:
output[:,1] = classifier.predict(X_test)
output_DF = pd.DataFrame(output.astype(int),columns=['PassengerId','Survived'])
output_DF.to_csv("./ud1.csv",index=False)
check_df = pd.read_csv('./ud1.csv')
print(check_df)

     PassengerId  Survived
0            892         0
1            893         0
2            894         1
3            895         1
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]
